### ISSUE TITLE
On NB1 pin reuse

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen-NB1-issues#1]
@stefanst says

On the NB1 wiring harness we have the following not populated pins:
1C, 1J, 1M
2G
3D, 3P, 3R

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports what shall we do with those unused pins? just a via hole or else?

**Comment by BeerMoneyMotorsports** [comment]
no current need to utilize them.  please apply short trace with through hole.  
![image](https://user-images.githubusercontent.com/82395131/128788688-e0894c3f-8fe3-483f-98c1-7af85da94fac.png)
