### ISSUE TITLE
AC pressure is it digital or analog?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen-NB1-issues#10]
@BeerMoneyMotorsports did we have some AC pressure drama on some other miata?

please link relevant tickets

please confirm which way is NB1 digital or analog

this is all related to analog input shortage if we go with ETB option

**Comment by BeerMoneyMotorsports** [comment]
https://github.com/rusefi/hellen64_miataNA6_94/issues/52

**Chatting with @BeerMoneyMotorsports we've figured out why we're seeing what we are (it's the diodes - it can't pull to ground, it can only pull to ground plus two diode drops).

@Qwerty-OFF Let's just route AC switch input to IN_AUX3. That has an integrated pullup, plus the divider gets us levels that might actually work as a plain digital input. If not, we can do it analog instead.**

@mck1117 will have to chime in on if it will be possible to utilize the digital input alone.  

![image](https://user-images.githubusercontent.com/82395131/129285444-836863de-9193-4c5c-bd1f-01b93945deb2.png)
NB1 is identical to NB2 for AC switch input.  We can utilize one of the dual type inputs like below. 

 - pin: 4F
    id: [GPIOB_0, EFI_ADC_8]
    class: [switch_inputs, analog_inputs]
    ts_name: 4F - AC_PRES/AUX1 (A23)
    function: A/C Pressure In

**Comment by andreika-git** [comment]
Done!
IN_AC_SW is on IN_AUX3:
![image](https://user-images.githubusercontent.com/15104768/132702296-a80d51eb-2af6-4829-8785-fd94ff6f21f5.png)
