### ISSUE TITLE
NB1 Tune

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellen-NB1-issues#19]
Need more info:
Fan 1 = Pin 1R (fixing yaml for name)
Fan 2 = Pin 1I (fixing yaml for type)
Boost Control Pin = 3T/4D

Done:
+Tach- 2k , Pulse=2
+AC switch = 1P
+AC Relay = 1S
+Check Engine = 1E
+Injector size = 256cc
+Ign 1 = 3G
+Idle solenoid Frequency = 320
+Clutch Down = 3I , Clutch down inverted = True

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports please clarify on top three lines

maybe a link to happy tune with those areas in question selected? we have per-dialog URL on rusEFI online

**Comment by BeerMoneyMotorsports** [comment]
Fan 1- was correctly set, i had to fix the ts_name in the yaml
Fan 2- Did not show up in the drop down in TS.  Had to fix the pin type in the yaml
Boost Control Pin is named 3T/4D.  Boost control goes to both of those Pins.  They use the same place on the chip, PF12.

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports did you mix things where I need to act with things where I did not need to act?
