### ISSUE TITLE
alternator control

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen-NB1-issues#20]
What's the deal with alternator control not connected on the PCB?

**Comment by BeerMoneyMotorsports** [comment]
@rusefillc what do you mean?  It is connected and works.

**Comment by rusefillc** [comment]
my bad, this schematics is a bit confusing :(

![image](https://user-images.githubusercontent.com/48498823/136886961-ebb6a54c-151f-4d5b-b2e5-7d57451134d5.png)
