### ISSUE TITLE
check engine pin

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen-NB1-issues#21]
note IO8 and OUT_IO8 two different things

i think yaml has wrong check engine pin?

see top-left corner vs bottom-right corner

![image](https://user-images.githubusercontent.com/48498823/136887381-6a717682-e5d9-48c7-a38d-5aca1c26c48b.png)

**Comment by BeerMoneyMotorsports** [comment]
Fixed, thank you for the alert
