### ISSUE TITLE
Tc4227 resistors

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellen-NB1-issues#24]
we need to apply this asap for nb1. New boards need to be ordered asap 

https://github.com/andreika-git/hellen-one/issues/118

**Comment by andreika-git** [comment]
The next rev NB1-b should use a new version of the output module with the fix: output-0.3

**Comment by andreika-git** [comment]
https://github.com/rusefi/hellen-NB1/commit/14446d4baaa8c47c5164bc8df8694c678db5f4b0

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/143564380-32ab77c0-70ce-414a-854e-63f9089b97ed.png)

**Comment by BeerMoneyMotorsports** [comment]
module updated for nb1.  closing
