### ISSUE TITLE
Alternator improvements based on NB2 damage

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellen-NB1-issues#25]
Miata OEM ecu uses a 1k resistor in series plus a 100nf cap to ground. We meed to match this in our circuit. 

![12FE66A8-EDD1-4AE6-B2BC-C0B9DFAF9556](https://user-images.githubusercontent.com/82395131/143894291-92803772-7c30-4c15-8ba7-54611d3154b1.jpeg)

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/143904815-6e722338-428f-436c-9470-bf4661a7ab23.png)

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports you want same on NB2

**Comment by BeerMoneyMotorsports** [comment]
@rusefillc yes, this ticket will be added to the main nb2 update list. 

https://github.com/rusefi/hellen-NB2-issues/issues/21

**Comment by BeerMoneyMotorsports** [comment]
@rusefillc yes, this ticket will be added to the main nb2 update list.

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports I am happy to help

![Image from iOS](https://user-images.githubusercontent.com/48498823/144121577-5b385d9f-95a4-4e10-9412-ca1848a4e4e7.jpg)

**Comment by rusefillc** [comment]
Status update: NB1 rev B being fabricated with new MCU module

See changelog https://github.com/rusefi/rusefi/wiki/Hellen-NB1

**Comment by andreika-git** [comment]
...with new Output-0.3 module

**Comment by BeerMoneyMotorsports** [comment]
Oliver has installed the resistor and cap upgrades several weeks ago.  To date, he has had no issues.  I will poke him for an update

**Comment by mck1117** [comment]
he mentioned on slack a few days ago that he's noticed no performance difference with the added RC, so we should be good to make the change

**Comment by BeerMoneyMotorsports** [comment]
Oliver reports 50kms and no issues

**Comment by BeerMoneyMotorsports** [comment]
the next batch, arriving tomorrow, have the new module and the alternator updates

**Comment by BeerMoneyMotorsports** [comment]
new module works as desired.  no faults yet.  will close now.
