### ISSUE TITLE
What PCB outline do we use?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen-NB1-issues#3]
2000 miata OEM case looks like NB2 case with 64 pin connector

2000 miata OEM does NOT look like NA6 or Frankenso case

![image](https://user-images.githubusercontent.com/48498823/124301251-89fcf600-db2d-11eb-9d6b-a26f16fbd578.png)

**Comment by rusefillc** [comment]
2000 camry looks like the winner to me

1) it looks to match NB1/NB2 OEM style so brackets might align

2) it looks to use a wide 125 connector OEM so we would be able to fit 76 pin connector

![image](https://user-images.githubusercontent.com/48498823/124302033-a0578180-db2e-11eb-9585-32f44fa6014b.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/124303884-f9281980-db30-11eb-8feb-b8b275d1088b.png)

**Comment by rusefillc** [comment]
@stefanst says that 2000 camry case would give us a mechanical interference with one of the Miata OEM ecu mounts?

**Comment by stefanst** [comment]
Fortunately, my memory was wrong. It looks like there won't be interference. The bracket mounts to the rear of the PCB

**Comment by rusefillc** [comment]
2000 camry case has arrived it totally works for us!

but two not one PCB to case mount and different location, more info later

**Comment by rusefillc** [comment]
Dimensions notes see pictures

![IMG_20210709_102623](https://user-images.githubusercontent.com/48498823/125094397-39434b00-e0a1-11eb-9628-e3a989da97b1.jpg)

![IMG_20210709_102826](https://user-images.githubusercontent.com/48498823/125094400-39434b00-e0a1-11eb-8e38-e30b07c74932.jpg)

![IMG_20210709_102450](https://user-images.githubusercontent.com/48498823/125094402-39dbe180-e0a1-11eb-927c-115bfdbbad86.jpg)

**Comment by rusefillc** [comment]
2000 camry case is very available, let's make NB1 board compatible ONLY with 2000camry case not with 1996camry

meaning we need two new mounting holes but we can remove existing mounting hole from the 1996camry location
