### ISSUE TITLE
STM32 144 shortage

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellen-NB1-issues#35]
The usual number of stm32f407zgt7 is not available.  I have found stm32f407zgt6 with large stock and low price.  I cannot see in the datasheet the difference between the two.  I need to know if this is applicable or not? @andreika-git @rusefillc @mck1117 

<img width="708" alt="image" src="https://user-images.githubusercontent.com/82395131/177657942-5eeea9c2-06e4-4e34-8e58-312834c7d1d6.png">

**Comment by mck1117** [comment]
6 and 7 are interchangable

**Comment by mck1117** [comment]
![image](https://user-images.githubusercontent.com/568254/177659787-4f7205b0-7c00-4a86-9e00-a9cdd4006c42.png)

**Comment by BeerMoneyMotorsports** [comment]
thank you!

**Comment by rusefillc** [comment]
See also https://github.com/andreika-git/hellen-one/issues/19
