### ISSUE TITLE
8/14/22 inventory shortage

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellen-NB1-issues#37]
U430,U430_... | TJA1051T/3/1J | SO8 | TJA1051T/3/1J l C38695

U300,U303 | RZ7899 | SO8 | rz7899 l C92373

**Comment by andreika-git** [comment]
U430,U430_... -- TJA1042T/3/1J C132227
U300,U303  -- RZ7889 | C83668

**Comment by rusefillc** [comment]
@andreika-git @BeerMoneyMotorsports 

U300,U303 -- RZ7889

does it actually do anything on any of the miata boards? shall we Do Not Populate to save $ and the planet?
