### ISSUE TITLE
NB1 + 96/97

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellen-NB1-issues#5]
@andreika-git i will be looking at 96/97 wiring to see if one ecu can manage both with minimal jumpers. Triggers will be different. Ill build a comparison spreadsheet for us to consider.

**Comment by andreika-git** [comment]
Can you share the 96/97 wiring? Do we have it on the wiki?

**Comment by BeerMoneyMotorsports** [comment]
http://neomiata.com/garage/Wiring%20Diagrams/Wiring%20Diagrams%201990-1996/1996_Miata%20System%20Wiring%20Diagrams.pdf

**Comment by BeerMoneyMotorsports** [comment]
![Uploading 7954EEC3-7184-46F6-BCBA-9BA1DF7D1074.png…]()

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports you need to allow it to upload before closing page see ^^^

**Comment by BeerMoneyMotorsports** [comment]
Fixed
