### ISSUE TITLE
Enlarge proto area

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen-NB1-issues#6]
please make proto more continues and overall large if possible

![image](https://user-images.githubusercontent.com/48498823/125175733-fdd97700-e19b-11eb-9c41-b86cd4083fe5.png)

**Comment by rusefillc** [comment]
@andreika-git poke

**Comment by andreika-git** [comment]
Done
![image](https://user-images.githubusercontent.com/15104768/132732205-46bafe2c-ad9c-4b53-9c38-0f5a03e84426.png)
