### ISSUE TITLE
Enlarge test pads

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen-NB1-issues#7]
Please make those closer to NB2 amazing huge size if possible with less than major effort

![image](https://user-images.githubusercontent.com/48498823/125175745-1ea1cc80-e19c-11eb-98c4-bf545e2d9301.png)

**Comment by andreika-git** [comment]
Done
![image](https://user-images.githubusercontent.com/15104768/132735209-e9034f45-c9fb-468d-abb8-18b178dc097b.png)
