### ISSUE TITLE
ETB controller

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellen-NB1-issues#9]
Reference below.  Add ETB functionality and board connector for I/O.  

https://github.com/rusefi/hellenNA6_issues/issues/14

**Comment by BeerMoneyMotorsports** [comment]
@andreika-git add on etb driver and vertical board mounted connector. Connector requires 10a capacity.

**Comment by rusefillc** [comment]
@andreika-git does https://github.com/rusefi/hellenNA6_issues/issues/14#issuecomment-895500346 have all the details needed?

**Comment by rusefillc** [comment]
@andreika-git says that we are out of space so one 6 pin connector is preferred for both TPS and PPS sensors and power. i.e. one shared GND for all four sensors and one shared +5v for all four sensors

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports we are starting to hit the limit of 16 analog inputs total 
see #10

@BeerMoneyMotorsports please link a google spreadsheet listing all analog inputs on NB1 it looks like we would have to start sharing. proposal is for optional ETB channels to overlap with optional  IN_PRESSURE, IN_TEMP, IN_EGR_BOOST

another option is to start looking into external ADC but that's a separate more complex story

**Comment by andreika-git** [comment]
Done!
![image](https://user-images.githubusercontent.com/15104768/132702021-725169bc-ea5a-4e71-80ca-7833e1787f09.png)
![image](https://user-images.githubusercontent.com/15104768/132702130-5ca94191-a726-44a8-a7d5-aa686ddc07cb.png)
